use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct RoadmapSource {
    pub source: &'static str,
    pub source_type: &'static str,
    pub product_types: &'static [&'static str],
    pub domains: &'static [&'static str],
    pub upstreams: &'static [&'static str],
    pub marketbridge_status: &'static str,
    pub priority: &'static str,
    pub notes: &'static str,
}

const QUOTE_BOOK_TRADE: &[&str] = &["market_quote", "market_order_book", "market_trade"];
const PERP_MARKET: &[&str] = &[
    "market_quote",
    "market_order_book",
    "market_trade",
    "market_funding",
    "market_open_interest",
    "market_liquidation",
];
const KLINE: &[&str] = &["market_kline"];
const DEX_QUOTE: &[&str] = &["market_quote", "dex_pool"];
const EXTERNAL_PRICE: &[&str] = &["market_quote"];
const LIQUIDATION: &[&str] = &["market_liquidation"];
const WALLET: &[&str] = &["onchain_transfer"];

const SPOT: &[&str] = &["spot"];
const PERP: &[&str] = &["perp"];
const SPOT_PERP: &[&str] = &["spot", "perp"];
const DEX: &[&str] = &["dex"];
const DATA_FEED: &[&str] = &["data_feed"];

const UP_HB_SPOT: &[&str] = &["hummingbot_exchange"];
const UP_HB_PERP: &[&str] = &["hummingbot_derivative"];
const UP_HB_CANDLES: &[&str] = &["hummingbot_candles_feed"];
const UP_HB_GATEWAY: &[&str] = &["hummingbot_gateway"];
const UP_HB_DATA: &[&str] = &["hummingbot_data_feed"];
const UP_HB_CCXT: &[&str] = &["hummingbot", "ccxt"];

pub fn source_roadmap() -> &'static [RoadmapSource] {
    ROADMAP
}

const ROADMAP: &[RoadmapSource] = &[
    RoadmapSource {
        source: "ascend_ex",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P2",
        notes: "Public spot WS order-book diffs and trades wired; BBO derived from book top.",
    },
    RoadmapSource {
        source: "backpack",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has spot/perp feed paths; remaining funding/OI/liquidation depth depends on venue support.",
    },
    RoadmapSource {
        source: "binance",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "Core spot/perp BBO, L2, trades, funding, OI, liquidations and klines are already wired.",
    },
    RoadmapSource {
        source: "bingx",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "MarketBridge has swap feed; complete funding/OI/liquidation coverage where public endpoints allow.",
    },
    RoadmapSource {
        source: "bitget",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "Spot/perp ticker paths exist; expand full L2/trades parity and liquidation coverage.",
    },
    RoadmapSource {
        source: "bitmart",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public spot depth/trades and perp depth/trades/funding/ticker are wired; OI/liquidation remain planned.",
    },
    RoadmapSource {
        source: "bitrue",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P3",
        notes: "Public spot simple-depth WS stream wired; trades remain planned.",
    },
    RoadmapSource {
        source: "bitstamp",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public spot order-book diff and trade feed are wired; REST snapshot/backfill remains planned.",
    },
    RoadmapSource {
        source: "btc_markets",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P3",
        notes: "Public spot order book and trades are wired; candle/backfill parity remains planned.",
    },
    RoadmapSource {
        source: "bybit",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "Core spot/perp BBO, L2, trades and liquidation paths are wired; keep parity with funding/OI coverage.",
    },
    RoadmapSource {
        source: "coinbase_advanced_trade",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has Coinbase spot ticker; add Coinbase Advanced L2/trades and Coinbase International separately.",
    },
    RoadmapSource {
        source: "cube",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P3",
        notes: "Public REST MBP snapshots wired with metadata scaling; protobuf WS diffs/trades remain planned.",
    },
    RoadmapSource {
        source: "derive",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public spot/perp order books and trades plus perp ticker funding are wired; OI/liquidation remain planned.",
    },
    RoadmapSource {
        source: "dexalot",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public CLOB DEX spot order books and trades are wired with EVM decimal conversion.",
    },
    RoadmapSource {
        source: "foxbit",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P3",
        notes: "Public Brazil spot REST order-book snapshots wired; WS trades remain planned.",
    },
    RoadmapSource {
        source: "gate_io",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has BBO paths; expand L2/trades/funding/OI/liquidation parity.",
    },
    RoadmapSource {
        source: "htx",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "MarketBridge has BBO paths; expand full depth/trades and derivatives analytics.",
    },
    RoadmapSource {
        source: "hyperliquid",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "Perp L2/trades/funding/OI are wired; add spot coverage and liquidation if public data is reliable.",
    },
    RoadmapSource {
        source: "injective_v2",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public LCD/Sentry spot/perp order books and trades wired; perp funding poller added.",
    },
    RoadmapSource {
        source: "kraken",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has spot/perp ticker paths; add L2/trades and derivatives parity.",
    },
    RoadmapSource {
        source: "kucoin",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has spot/perp ticker paths; add L2/trades/funding/OI/liquidation parity.",
    },
    RoadmapSource {
        source: "mexc",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "MarketBridge has spot/futures depth and trade feed; finish funding/OI/liquidation where available.",
    },
    RoadmapSource {
        source: "ndax",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P3",
        notes: "Public Canadian spot L2 snapshots wired via GetInstruments/GetL2Snapshot; trades remain planned.",
    },
    RoadmapSource {
        source: "okx",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "Core spot/perp BBO, L2, trades, funding, OI, liquidations and klines are wired.",
    },
    RoadmapSource {
        source: "paper_trade",
        source_type: "synthetic",
        product_types: DATA_FEED,
        domains: &[],
        upstreams: UP_HB_SPOT,
        marketbridge_status: "ignored",
        priority: "P4",
        notes: "Execution simulator, intentionally out of scope for MarketBridge data-only boundary.",
    },
    RoadmapSource {
        source: "vertex",
        source_type: "exchange",
        product_types: SPOT_PERP,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public CLOB spot/perp book-depth and trade streams wired for known product ids.",
    },
    RoadmapSource {
        source: "xrpl",
        source_type: "exchange",
        product_types: SPOT,
        domains: QUOTE_BOOK_TRADE,
        upstreams: UP_HB_SPOT,
        marketbridge_status: "partial",
        priority: "P2",
        notes: "Public book_offers snapshots wired; issuer-aware mapping currently includes XRP/USD.",
    },
    RoadmapSource {
        source: "aevo",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_PERP,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public perp order books/trades wired over WS; funding and instrument BBO via REST.",
    },
    RoadmapSource {
        source: "architect",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_PERP,
        marketbridge_status: "partial",
        priority: "P2",
        notes: "Read-only perp WS book/trade and REST funding wired; bearer token required.",
    },
    RoadmapSource {
        source: "decibel",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_PERP,
        marketbridge_status: "partial",
        priority: "P2",
        notes: "Read-only Aptos Decibel perp depth/trade/market_price streams wired; bearer token required.",
    },
    RoadmapSource {
        source: "evedex",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_PERP,
        marketbridge_status: "partial",
        priority: "P2",
        notes: "Public perp REST order books, recent trades, and funding metrics wired.",
    },
    RoadmapSource {
        source: "grvt",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public perp book/trade/ticker streams wired; ticker emits funding and open interest.",
    },
    RoadmapSource {
        source: "pacifica",
        source_type: "exchange",
        product_types: PERP,
        domains: PERP_MARKET,
        upstreams: UP_HB_CCXT,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "Public perp book/trades/prices wired; prices emit funding and open interest.",
    },
    RoadmapSource {
        source: "jupiter",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "Quote poller is wired; expand route metadata and slippage curves.",
    },
    RoadmapSource {
        source: "meteora",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "DexScreener-backed Solana Meteora pool quote snapshots wired; DLMM-native state remains planned.",
    },
    RoadmapSource {
        source: "raydium",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "Basic price poller is wired; expand AMM/CLMM pool state.",
    },
    RoadmapSource {
        source: "orca",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P1",
        notes: "Hummingbot Gateway active CLMM connector; useful Solana liquidity source.",
    },
    RoadmapSource {
        source: "uniswap",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "MarketBridge has Uniswap V3 pool poller; expand V2, universal router, and pool liquidity curves.",
    },
    RoadmapSource {
        source: "pancakeswap",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P1",
        notes: "Hummingbot Gateway active connector; add BNB/EVM DEX coverage.",
    },
    RoadmapSource {
        source: "balancer",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P2",
        notes: "Hummingbot Gateway legacy connector; useful weighted pool source.",
    },
    RoadmapSource {
        source: "curve",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P2",
        notes: "Hummingbot Gateway legacy connector; useful stable-swap and depeg signal source.",
    },
    RoadmapSource {
        source: "sushiswap",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P2",
        notes: "Hummingbot Gateway legacy connector; add after EVM DEX abstraction is stable.",
    },
    RoadmapSource {
        source: "quickswap",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P2",
        notes: "Hummingbot Gateway legacy Polygon connector.",
    },
    RoadmapSource {
        source: "traderjoe",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P2",
        notes: "Hummingbot Gateway legacy Avalanche connector.",
    },
    RoadmapSource {
        source: "etcswap",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_GATEWAY,
        marketbridge_status: "planned",
        priority: "P3",
        notes: "Hummingbot Gateway legacy Ethereum Classic connector.",
    },
    RoadmapSource {
        source: "candles_feed",
        source_type: "data_feed",
        product_types: DATA_FEED,
        domains: KLINE,
        upstreams: UP_HB_CANDLES,
        marketbridge_status: "partial",
        priority: "P0",
        notes: "Hummingbot has many venue-specific candles; MarketBridge currently persists Binance/OKX and live tick bars.",
    },
    RoadmapSource {
        source: "coin_cap",
        source_type: "aggregate_data",
        product_types: DATA_FEED,
        domains: EXTERNAL_PRICE,
        upstreams: UP_HB_DATA,
        marketbridge_status: "implemented",
        priority: "P2",
        notes: "Optional REST aggregate USD price feed is wired as market_quote.",
    },
    RoadmapSource {
        source: "coin_gecko",
        source_type: "aggregate_data",
        product_types: DATA_FEED,
        domains: EXTERNAL_PRICE,
        upstreams: UP_HB_DATA,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "CoinGecko poller is wired.",
    },
    RoadmapSource {
        source: "custom_api",
        source_type: "external_event",
        product_types: DATA_FEED,
        domains: &["external_signal"],
        upstreams: UP_HB_DATA,
        marketbridge_status: "implemented",
        priority: "P2",
        notes: "Generic numeric/JSON external signal pollers are wired through aggregates.custom_apis.",
    },
    RoadmapSource {
        source: "binance_liquidations_feed",
        source_type: "data_feed",
        product_types: PERP,
        domains: LIQUIDATION,
        upstreams: UP_HB_DATA,
        marketbridge_status: "implemented",
        priority: "P0",
        notes: "MarketBridge already wires Binance liquidation feed.",
    },
    RoadmapSource {
        source: "wallet_tracker",
        source_type: "onchain",
        product_types: DATA_FEED,
        domains: WALLET,
        upstreams: UP_HB_DATA,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "MarketBridge has Whale Alert, mempool.space, and Etherscan watchlist; extend wallet tracker semantics.",
    },
    RoadmapSource {
        source: "amm_gateway_data_feed",
        source_type: "defi_venue",
        product_types: DEX,
        domains: DEX_QUOTE,
        upstreams: UP_HB_DATA,
        marketbridge_status: "partial",
        priority: "P1",
        notes: "MarketBridge has standalone DeFi pollers; add Gateway-style multi-protocol feed abstraction.",
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roadmap_contains_hummingbot_only_sources() {
        let sources = source_roadmap()
            .iter()
            .map(|row| row.source)
            .collect::<std::collections::HashSet<_>>();

        assert!(sources.contains("bitmart"));
        assert!(sources.contains("aevo"));
        assert!(sources.contains("meteora"));
        assert!(sources.contains("coin_cap"));
    }

    #[test]
    fn roadmap_preserves_data_only_boundary() {
        let paper = source_roadmap()
            .iter()
            .find(|row| row.source == "paper_trade")
            .expect("paper trade row");

        assert_eq!(paper.marketbridge_status, "ignored");
        assert!(paper.notes.contains("out of scope"));
    }
}
